[project]
name = "lab5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ale-py>=0.10.0",
    "gymnasium[accept-rom-license,atari]==1.1.1",
    "imageio[ffmpeg]>=2.37.3",
    "opencv-python>=4.13.0.92",
    "wandb>=0.26.0",
]
